<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Kuddle.Extensions.Configuration.Tests</RootNamespace>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.3.2" />
    <PackageReference Include="TUnit" Version="1.11.16" />
  </ItemGroup>
</Project>
