<Project>
  <PropertyGroup>
    <ArtifactsPath>$(MSBuildThisFileDirectory)..\.artifacts</ArtifactsPath>
    <!-- Build Properties -->
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <!-- NuGet Package Properties -->
    <Authors>jamesshenry, xoko14</Authors>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/xoko14/Kuddle.Net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/xoko14/Kuddle.Net</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <MinVerDefaultPreReleaseIdentifiers>preview</MinVerDefaultPreReleaseIdentifiers>
    <Deterministic>true</Deterministic>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'"
      >true</ContinuousIntegrationBuild
    >
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MinVer" Version="6.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Analyzers" Version="4.15.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="4.15.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="4.15.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>
  <!-- NuGet Package Files -->
  <ItemGroup>
    <None
      Include="$(MSBuildThisFileDirectory)..\readme.md"
      Pack="true"
      PackagePath="\"
      Condition="Exists('$(MSBuildThisFileDirectory)..\readme.md')"
    />
    <None
      Include="$(MSBuildThisFileDirectory)..\LICENSE.md"
      Pack="true"
      PackagePath="\"
      Condition="Exists('$(MSBuildThisFileDirectory)..\LICENSE.md')"
    />
    <None
      Include="$(MSBuildThisFileDirectory)..\.build\assets\icon.png"
      Pack="true"
      PackagePath="\"
      Condition="Exists('$(MSBuildThisFileDirectory)..\.build\assets\icon.png')"
    />
  </ItemGroup>
</Project>
